### ISSUE TITLE
Amzn

### ISSUE THREAD

**Issue by KiaN2020** [WHTJEON/narrowvine-reborn#12]
Does anyone know how to get this working with Amzn Prime

I do the same as for other websites

Enter MPD Url:

Enter License Url:

it then says

[info] Attempting Widevine challenge...
[info] Getting Keys...
ERROR: cannot open input (-4)
Traceback (most recent call last):
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 235, in <module>
    KEYS = do_decrypt(licurl=licurl, kid=get_kid(),headers=headers)
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 161, in do_decrypt
    pssh = createpsshfromkid(kid)
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 158, in createpsshfromkid
    return get_pssh(kid).decode('utf-8')
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 151, in get_pssh
    array_of_bytes.extend(bytes.fromhex(keyId.replace('-', '')))
ValueError: non-hexadecimal number found in fromhex() arg at position 0

it works with other sites but for amzn it does not seem to work or I am missing some extra steps that are needed for this particular site.

**Comment by zhjb7** [comment]
I think you should add some license headers.

**Comment by KiaN2020** [comment]
> I think you should add some license headers.

Okay I will try adding license headers and see if that works.

**Comment by KiaN2020** [comment]
Not tried adding headers yet as I noticed that there was a few different mpd urls and License urls so just out of curiosity I thought I would try some different ones just to see if they would all give the same error as in my original post or anything different.

upon trying different ones I managed to get it to download the Video and Audio but it then gives a different error:

[info] Attempting Widevine challenge...
[info] Getting Keys...
unable to parse license - check protobufs
[info] Found Key!
Traceback (most recent call last):
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 245, in <module>
    print ("[info] Decrypting Audio Using KEY: " + keysOnly(KEYS))
  File "/Volumes/Main HD/WHTJEON : narrowvine-reborn/narrowvine-reborn-master/narrowvine_reborn.py", line 176, in keysOnly
    return key
UnboundLocalError: local variable 'key' referenced before assignment
