### ISSUE TITLE
UnboundLocalError: local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by mujehoxe** [WHTJEON/narrowvine-reborn#9]
```
[info] Attempting Widevine challenge...
[info] Getting Keys...
unable to parse license - check protobufs
[info] Found Key!
Traceback (most recent call last):
  File "/ext/Downloads/narrowvine-reborn-master/narrowvine_reborn.py", line 245, in <module>
    print ("[info] Decrypting Audio Using KEY: " + keysOnly(KEYS))
  File "/ext/Downloads/narrowvine-reborn-master/narrowvine_reborn.py", line 176, in keysOnly
    return key
UnboundLocalError: local variable 'key' referenced before assignment
```

**Comment by WHTJEON** [comment]
Wrong license url or license header
